// OX 퀴즈 데이터
export const OX_QUESTIONS = 
[
  {"q": "파이썬에서 변수는 선언 시 자료형을 명시하지 않아도 된다.", "answer": true},
  {"q": "print() 함수의 기본 구분자(sep)는 쉼표(,)이다.", "answer": false},
  {"q": "리스트(list)는 대괄호 []를 사용하여 생성한다.", "answer": true},
  {"q": "딕셔너리(dict)의 key는 중복을 허용한다.", "answer": false},
  {"q": "튜플(tuple)은 생성 후 요소의 값을 변경할 수 없다.", "answer": true},
  {"q": "문자열(string)은 인덱싱을 통해 개별 문자를 변경할 수 있다.", "answer": false},
  {"q": "집합(set)은 중복된 값을 허용하지 않는다.", "answer": true},
  {"q": "for문에서 range(1, 10, 2)는 1부터 10까지 짝수를 생성한다.", "answer": false},
  {"q": "while문은 조건이 참(True)인 동안 반복 실행된다.", "answer": true},
  {"q": "파이썬에서 들여쓰기(indentation)는 코드 실행에 영향을 주지 않는다.", "answer": false},
  {"q": "함수에서 return문이 없으면 자동으로 0을 반환한다.", "answer": false},
  {"q": "if-elif-else 구문에서 elif는 여러 번 사용할 수 있다.", "answer": true},
  {"q": "람다(lambda) 함수는 여러 줄의 문장을 포함할 수 있다.", "answer": false},
  {"q": "함수는 def 키워드로 정의한다.", "answer": true},
  {"q": "self는 파이썬의 예약어(keyword)이다.", "answer": false},
  {"q": "함수의 매개변수에는 기본값을 지정할 수 있다.", "answer": true},
  {"q": "파이썬은 다중 상속(multiple inheritance)을 지원하지 않는다.", "answer": false},
  {"q": "*args는 여러 개의 위치 인자를 튜플로 받는다.", "answer": true},
  {"q": "except 블록 없이 try 블록만 단독으로 사용할 수 있다.", "answer": false},
  {"q": "**kwargs는 여러 개의 키워드 인자를 딕셔너리로 받는다.", "answer": true},
  {"q": "ZeroDivisionError는 문자열을 정수로 변환할 때 발생하는 예외이다.", "answer": false},
  {"q": "클래스는 class 키워드로 정의한다.", "answer": true},
  {"q": "딕셔너리는 순서가 보장되지 않는 자료구조이며 파이썬 3.7 이상에서도 마찬가지이다.", "answer": false},
  {"q": "__init__ 메서드는 객체가 생성될 때 자동으로 호출된다.", "answer": true},
  {"q": "append() 메서드는 리스트의 특정 인덱스에 요소를 삽입한다.", "answer": false},
  {"q": "클래스의 인스턴스 변수는 self를 통해 접근한다.", "answer": true},
  {"q": "파이썬에서 == 연산자와 is 연산자는 항상 동일한 결과를 반환한다.", "answer": false},
  {"q": "try-except 구문은 예외 처리를 위해 사용된다.", "answer": true},
  {"q": "정수(int)와 실수(float)를 더하면 항상 오류가 발생한다.", "answer": false},
  {"q": "finally 블록은 예외 발생 여부와 관계없이 항상 실행된다.", "answer": true},
  {"q": "변수명은 숫자로 시작할 수 있다.", "answer": false},
  {"q": "raise 키워드를 사용하여 예외를 직접 발생시킬 수 있다.", "answer": true},
  {"q": "파이썬에서 세미콜론(;)은 문장의 끝에 반드시 필요하다.", "answer": false},
  {"q": "import 키워드를 사용하여 외부 모듈을 가져올 수 있다.", "answer": true},
  {"q": "딕셔너리의 값(value)은 키(key)와 마찬가지로 변경 불가능한(immutable) 자료형만 가능하다.", "answer": false},
  {"q": "len() 함수는 리스트, 문자열, 딕셔너리 등의 길이를 반환한다.", "answer": true},
  {"q": "continue문은 반복문을 즉시 종료시킨다.", "answer": false},
  {"q": "pop() 메서드는 리스트에서 요소를 제거하고 그 값을 반환한다.", "answer": true},
  {"q": "파이썬의 리스트는 서로 다른 자료형의 요소를 함께 저장할 수 없다.", "answer": false},
  {"q": "슬라이싱(slicing)은 콜론(:)을 사용하여 범위를 지정한다.", "answer": true},
  {"q": "빈 중괄호 {}는 빈 set을 생성한다.", "answer": false},
  {"q": "not, and, or는 파이썬의 논리 연산자이다.", "answer": true},
  {"q": "파이썬의 for문은 반드시 range() 함수와 함께 사용해야 한다.", "answer": false},
  {"q": "boolean 자료형은 True와 False 두 가지 값을 가진다.", "answer": true},
  {"q": "정수와 문자열은 + 연산자로 바로 연결할 수 있다.", "answer": false},
  {"q": "type() 함수는 변수의 자료형을 반환한다.", "answer": true},
  {"q": "int(\"3.5\")는 정상적으로 3을 반환한다.", "answer": false},
  {"q": "변수명에는 언더스코어(_)를 사용할 수 있다.", "answer": true},
  {"q": "나눗셈 연산자 //는 항상 실수(float)를 반환한다.", "answer": false},
  {"q": "문자열은 단일 인용부호(')나 이중 인용부호(\")로 생성할 수 있다.", "answer": true},
  {"q": "파이썬에서 == 연산자는 대입(assignment)에 사용된다.", "answer": false},
  {"q": "break문은 반복문을 즉시 종료시킨다.", "answer": true},
  {"q": "파이썬 리스트의 인덱스는 1부터 시작한다.", "answer": false},
  {"q": "함수 내부에서 global 키워드를 사용하면 전역 변수를 수정할 수 있다.", "answer": true},
  {"q": "sorted() 함수는 원본 리스트를 직접 변경한다.", "answer": false},
  {"q": "딕셔너리는 key:value 쌍으로 데이터를 저장한다.", "answer": true},
  {"q": "튜플은 소괄호 없이 생성할 수 없다.", "answer": false},
  {"q": "set 자료형은 중괄호 { }를 사용하여 생성할 수 있다.", "answer": true},
  {"q": "리스트와 튜플은 모두 변경 가능한(mutable) 자료형이다.", "answer": false},
  {"q": "빈 딕셔너리는 dict() 또는 {}로 생성할 수 있다.", "answer": true},
  {"q": "클래스 변수(class variable)는 모든 인스턴스가 공유하지 않는다.", "answer": false},
  {"q": "빈 set은 set()으로 생성해야 한다.", "answer": true},
  {"q": "파이썬에서 함수는 여러 개의 값을 동시에 반환할 수 없다.", "answer": false},
  {"q": "문자열은 + 연산자로 연결(concatenation)할 수 있다.", "answer": true},
  {"q": "pass 키워드는 반복문을 종료시킨다.", "answer": false},
  {"q": "int() 함수는 문자열이나 실수를 정수로 변환할 수 있다.", "answer": true},
  {"q": "try-except 구문에서 else 블록은 사용할 수 없다.", "answer": false},
  {"q": "float() 함수는 정수나 문자열을 실수로 변환할 수 있다.", "answer": true},
  {"q": "open() 함수로 연 파일은 close()를 호출하지 않아도 항상 자동으로 닫힌다.", "answer": false},
  {"q": "나눗셈 연산자 /는 항상 실수(float)를 반환한다.", "answer": true},
  {"q": "정수형 변수는 한 번 선언되면 자료형을 바꿀 수 없다.", "answer": false},
  {"q": "% 연산자는 나눗셈의 나머지를 반환한다.", "answer": true},
  {"q": "비교 연산자 !=는 두 값이 같은지를 확인한다.", "answer": false},
  {"q": "리스트는 인덱스를 통해 특정 요소에 접근할 수 있다.", "answer": true},
  {"q": "파이썬의 함수는 다른 함수의 인자로 전달할 수 없다.", "answer": false},
  {"q": "sort() 메서드는 리스트를 원본에서 직접 정렬한다.", "answer": true},
  {"q": "리스트의 길이를 구할 때는 length() 메서드를 사용한다.", "answer": false},
  {"q": "del 키워드를 사용하여 리스트의 요소를 삭제할 수 있다.", "answer": true},
  {"q": "range(5)는 1부터 5까지의 정수를 생성한다.", "answer": false},
  {"q": "딕셔너리에서 존재하지 않는 key로 접근하면 KeyError가 발생한다.", "answer": true},
  {"q": "리스트 컴프리헨션은 소괄호 ()를 사용하여 작성한다.", "answer": false},
  {"q": "클래스의 메서드는 첫 번째 매개변수로 self를 받는 것이 일반적이다.", "answer": true},
  {"q": "파이썬의 주석은 //로 시작한다.", "answer": false},
  {"q": "상속을 받은 자식 클래스는 부모 클래스의 메서드를 사용할 수 있다.", "answer": true},
  {"q": "in 연산자는 컬렉션에 특정 값이 몇 번 등장하는지 횟수를 반환한다.", "answer": false},
  {"q": "super() 함수는 부모 클래스의 메서드를 호출할 때 사용한다.", "answer": true},
  {"q": "str() 함수는 문자열을 정수로 변환한다.", "answer": false},
  {"q": "pass 키워드는 아무 동작도 하지 않는 자리표시자(placeholder)이다.", "answer": true},
  {"q": "** 연산자는 두 값을 나눈 나머지를 계산한다.", "answer": false},
  {"q": "예외 처리에서 여러 개의 except 블록을 사용할 수 있다.", "answer": true},
  {"q": "음수 인덱스를 사용하면 항상 IndexError가 발생한다.", "answer": false},
  {"q": "with문은 파일과 같은 리소스를 자동으로 닫아준다.", "answer": true},
  {"q": "딕셔너리의 get() 메서드는 key가 없을 때 항상 KeyError를 발생시킨다.", "answer": false},
  {"q": "부울(bool) 값 True는 정수 1과 같은 값으로 취급될 수 있다.", "answer": true},
  {"q": "docstring은 코드 실행 시 항상 자동으로 화면에 출력된다.", "answer": false},
  {"q": "None은 값이 없음을 나타내는 파이썬의 특수한 자료형이다.", "answer": true},
  {"q": "파이썬에서 모든 값은 객체가 아니라 원시 자료형(primitive type)으로 처리된다.", "answer": false},
  {"q": "함수는 다른 함수 내부에 정의할 수 있다(중첩 함수).", "answer": true},
  {"q": "== 연산자는 두 변수의 메모리 주소가 같은지를 비교한다.", "answer": false},
  {"q": "딕셔너리의 키(key)는 변경 불가능한(immutable) 자료형이어야 한다.", "answer": true}
];
