// OX 퀴즈 데이터
export const OX_QUESTIONS = [
  { q: "파이썬에서 print('Hello')를 실행하면 Hello가 출력된다.", answer: true },
  { q: "파이썬 인덱스는 0부터 시작한다.", answer: true },
  { q: "문자열의 마지막 글자는 인덱스 [-1]로 접근할 수 있다.", answer: true },
  { q: "파이썬에서 'A' + 'B'의 결과는 'AB'이다.", answer: true },
  { q: "파이썬에서 변수 이름은 숫자로 시작할 수 있다.", answer: false },
  { q: "파이썬에서 // 연산자는 정수 나눗셈(몫)을 구한다.", answer: true },
  { q: "파이썬에서 True와 False는 대소문자를 구분하지 않는다.", answer: false },
  { q: "파이썬 리스트는 여러 자료형을 함께 저장할 수 있다.", answer: true },
  { q: "파이썬에서 len('Python')의 결과는 6이다.", answer: true },
  { q: "range(5)는 0부터 5까지(총 6개) 반복한다.", answer: false },
  { q: "파이썬에서 if 조건문은 콜론(:)으로 끝난다.", answer: true },
  { q: "파이썬에서 def는 함수를 정의할 때 사용한다.", answer: true },
  { q: "리스트의 append()는 맨 앞에 요소를 추가한다.", answer: false },
  { q: "파이썬에서 딕셔너리의 키(key)는 중복될 수 있다.", answer: false },
  { q: "파이썬에서 type(3.14)의 결과는 float이다.", answer: true },
  { q: "파이썬에서 while True:는 무한 루프를 만든다.", answer: true },
  { q: "파이썬에서 문자열은 불변(immutable)이다.", answer: true },
  { q: "파이썬에서 try-except는 에러를 처리하는 데 사용된다.", answer: true },
  { q: "파이썬에서 lambda는 이름 없는 함수를 만든다.", answer: true },
  { q: "파이썬에서 class는 객체를 생성하는 틀이다.", answer: true },
  { q: "파이썬에서 break는 현재 반복문을 즉시 종료한다.", answer: true },
  { q: "파이썬에서 continue는 반복문을 완전히 종료한다.", answer: false },
  { q: "파이썬에서 str(123)의 결과는 '123'이다.", answer: true },
  { q: "리스트 슬라이싱 [1:3]은 인덱스 1과 3의 요소를 반환한다.", answer: false },
  { q: "파이썬에서 import는 외부 모듈을 불러올 때 사용한다.", answer: true },
  { q: "파이썬에서 None은 아무 값도 없음을 나타낸다.", answer: true },
  { q: "파이썬에서 2 ** 3의 결과는 8이다.", answer: true },
  { q: "파이썬에서 input()함수는 항상 정수를 반환한다.", answer: false },
  { q: "파이썬에서 set은 중복 값을 허용하지 않는다.", answer: true },
  { q: "파이썬에서 튜플(tuple)은 생성 후 값을 변경할 수 있다.", answer: false },
  { q: "파이썬에서 'hello'.upper()의 결과는 'HELLO'이다.", answer: true },
  { q: "파이썬에서 리스트는 대괄호 []로 생성한다.", answer: true },
  { q: "파이썬에서 딕셔너리는 순서가 없다. (Python 3.7 이전 기준)", answer: true },
  { q: "파이썬에서 % 연산자는 나머지를 구한다.", answer: true },
  { q: "파이썬에서 is 연산자는 두 변수의 값이 같은지 비교한다.", answer: false },
];
