name: Notion Sync

on:
  push:
    branches: [ main ]
    paths:
      - '**.md' # 마크다운(.md) 파일이 푸시될 때만 작동해!

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push MD to Notion
        uses: anyer9/github-action-md-to-notion@v1
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-page-id: ${{ secrets.NOTION_PAGE_ID }}
          file-path: './AI_MON_기획안.md' # 노션으로 보낼 메인 파일 이름