// ═══════════════════════════════════════════════════════════════
//  bombQuestions.js — 문제 데이터 (칠판 박스 내용)
//  tokens: 칠판에 표시될 코드 조각들
//    t     : 표시 텍스트
//    type  : 색상 분류 'fn' | 'str' | 'punc' | 'kw' | 'num'
//            (키워드/함수·메서드 호출은 전부 'kw', 문자열은 'str', 숫자는 'num')
//    error : true 인 토큰이 정답(터치해야 할 오류) — 항상 type: 'kw'
//    fix   : 올바른 코드(정답 후 표시)
//
//  전 문제 패턴 ① 철자 오타 — 파이썬 키워드 철자를 살짝 틀림 (예: whlie → while)
//  총 50문제, 스테이지 시작 시 순서를 섞음(shuffle)
// ═══════════════════════════════════════════════════════════════

export function shuffle(arr) {
  return [...arr].sort(() => Math.random() - 0.5);
}

const RAW_QUESTIONS = [
  {
    id: 1,
    tokens: [
      { t: 'fed', type: 'kw', error: true, fix: 'def' },
      { t: ' ', type: 'punc' },
      { t: 'greet', type: 'kw' },
      { t: '(name):\n    ', type: 'punc' },
      { t: '""', type: 'str' },
      { t: '"이름으로 인사하기"', type: 'str' },
      { t: '""', type: 'str' },
      { t: '\n    message = ', type: 'punc' },
      { t: 'f"안녕, {name}!"', type: 'str' },
      { t: '\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(message)\n    ', type: 'punc' },
      { t: 'return', type: 'kw' },
      { t: ' message', type: 'punc' },
    ],
    hint: '함수를 정의하는 키워드 철자를 확인하세요',
  },
  {
    id: 2,
    tokens: [
      { t: 'deff', type: 'kw', error: true, fix: 'def' },
      { t: ' ', type: 'punc' },
      { t: 'calc_total', type: 'kw' },
      { t: '(price, qty):\n    total = price * qty\n    tax = total * ', type: 'punc' },
      { t: '0.1', type: 'num' },
      { t: '\n    ', type: 'punc' },
      { t: 'return', type: 'kw' },
      { t: ' total + tax', type: 'punc' },
    ],
    hint: '함수를 정의하는 키워드 철자를 확인하세요',
  },
  {
    id: 3,
    tokens: [
      { t: 'df', type: 'kw', error: true, fix: 'def' },
      { t: ' ', type: 'punc' },
      { t: 'is_even', type: 'kw' },
      { t: '(n):\n    ', type: 'punc' },
      { t: 'if', type: 'kw' },
      { t: ' n % ', type: 'punc' },
      { t: '2', type: 'num' },
      { t: ' == ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: ':\n        ', type: 'punc' },
      { t: 'return', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'True', type: 'kw' },
      { t: '\n    ', type: 'punc' },
      { t: 'return', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'False', type: 'kw' },
    ],
    hint: '함수를 정의하는 키워드 철자를 확인하세요',
  },
  {
    id: 4,
    tokens: [
      { t: 'edf', type: 'kw', error: true, fix: 'def' },
      { t: ' ', type: 'punc' },
      { t: 'send_email', type: 'kw' },
      { t: '(to, subject):\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: 'f"받는사람: {to}"', type: 'str' },
      { t: ')\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: 'f"제목: {subject}"', type: 'str' },
      { t: ')\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"전송 완료!"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '함수를 정의하는 키워드 철자를 확인하세요',
  },
  {
    id: 5,
    tokens: [
      { t: 'fi', type: 'kw', error: true, fix: 'if' },
      { t: ' age >= ', type: 'punc' },
      { t: '18', type: 'num' },
      { t: ':\n    status = ', type: 'punc' },
      { t: '"성인"', type: 'str' },
      { t: '\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    status = ', type: 'punc' },
      { t: '"미성년자"', type: 'str' },
      { t: '\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(status)', type: 'punc' },
    ],
    hint: '조건문을 시작하는 키워드 철자를 확인하세요',
  },
  {
    id: 6,
    tokens: [
      { t: 'iif', type: 'kw', error: true, fix: 'if' },
      { t: ' score >= ', type: 'punc' },
      { t: '90', type: 'num' },
      { t: ':\n    grade = ', type: 'punc' },
      { t: '"A"', type: 'str' },
      { t: '\n', type: 'punc' },
      { t: 'elif', type: 'kw' },
      { t: ' score >= ', type: 'punc' },
      { t: '80', type: 'num' },
      { t: ':\n    grade = ', type: 'punc' },
      { t: '"B"', type: 'str' },
      { t: '\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    grade = ', type: 'punc' },
      { t: '"C"', type: 'str' },
    ],
    hint: '조건문을 시작하는 키워드 철자를 확인하세요',
  },
  {
    id: 7,
    tokens: [
      { t: 'ifs', type: 'kw', error: true, fix: 'if' },
      { t: ' balance < ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"잔액 부족"', type: 'str' },
      { t: ')\n    overdraft = ', type: 'punc' },
      { t: 'True', type: 'kw' },
      { t: '\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    overdraft = ', type: 'punc' },
      { t: 'False', type: 'kw' },
    ],
    hint: '조건문을 시작하는 키워드 철자를 확인하세요',
  },
  {
    id: 8,
    tokens: [
      { t: 'if_', type: 'kw', error: true, fix: 'if' },
      { t: ' username == ', type: 'punc' },
      { t: '""', type: 'str' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"이름을 입력하세요"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: 'f"환영합니다, {username}"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '조건문을 시작하는 키워드 철자를 확인하세요',
  },
  {
    id: 9,
    tokens: [
      { t: 'if', type: 'kw' },
      { t: ' temperature > ', type: 'punc' },
      { t: '30', type: 'num' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"더워요"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'esle', type: 'kw', error: true, fix: 'else' },
      { t: '\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"괜찮아요"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"오늘 날씨 확인 완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '조건이 아닐 때 실행되는 키워드 철자를 확인하세요',
  },
  {
    id: 10,
    tokens: [
      { t: 'if', type: 'kw' },
      { t: ' is_logged_in:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"환영합니다"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'elese', type: 'kw', error: true, fix: 'else' },
      { t: '\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"로그인이 필요합니다"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"페이지 로딩 완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '조건이 아닐 때 실행되는 키워드 철자를 확인하세요',
  },
  {
    id: 11,
    tokens: [
      { t: 'if', type: 'kw' },
      { t: ' cart_count > ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"장바구니 확인"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'els', type: 'kw', error: true, fix: 'else' },
      { t: '\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"장바구니가 비었습니다"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"확인 완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '조건이 아닐 때 실행되는 키워드 철자를 확인하세요',
  },
  {
    id: 12,
    tokens: [
      { t: 'if', type: 'kw' },
      { t: ' attempts < ', type: 'punc' },
      { t: '3', type: 'num' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"다시 시도하세요"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'ellse', type: 'kw', error: true, fix: 'else' },
      { t: '\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"계정이 잠겼습니다"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"로그인 시도 종료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '조건이 아닐 때 실행되는 키워드 철자를 확인하세요',
  },
  {
    id: 13,
    tokens: [
      { t: 'if', type: 'kw' },
      { t: ' x > ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: ':\n    sign = ', type: 'punc' },
      { t: '"양수"', type: 'str' },
      { t: '\n', type: 'punc' },
      { t: 'elfi', type: 'kw', error: true, fix: 'elif' },
      { t: '\n    x == ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: ':\n    sign = ', type: 'punc' },
      { t: '"0"', type: 'str' },
      { t: '\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    sign = ', type: 'punc' },
      { t: '"음수"', type: 'str' },
    ],
    hint: '추가 조건을 검사하는 키워드 철자를 확인하세요',
  },
  {
    id: 14,
    tokens: [
      { t: 'if', type: 'kw' },
      { t: ' day == ', type: 'punc' },
      { t: '"월"', type: 'str' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"월요일"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'elifi', type: 'kw', error: true, fix: 'elif' },
      { t: '\n    day == ', type: 'punc' },
      { t: '"화"', type: 'str' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"화요일"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"기타 요일"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '추가 조건을 검사하는 키워드 철자를 확인하세요',
  },
  {
    id: 15,
    tokens: [
      { t: 'if', type: 'kw' },
      { t: ' level == ', type: 'punc' },
      { t: '1', type: 'num' },
      { t: ':\n    reward = ', type: 'punc' },
      { t: '10', type: 'num' },
      { t: '\n', type: 'punc' },
      { t: 'eilf', type: 'kw', error: true, fix: 'elif' },
      { t: '\n    level == ', type: 'punc' },
      { t: '2', type: 'num' },
      { t: ':\n    reward = ', type: 'punc' },
      { t: '20', type: 'num' },
      { t: '\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    reward = ', type: 'punc' },
      { t: '30', type: 'num' },
    ],
    hint: '추가 조건을 검사하는 키워드 철자를 확인하세요',
  },
  {
    id: 16,
    tokens: [
      { t: 'whlie', type: 'kw', error: true, fix: 'while' },
      { t: ' count < ', type: 'punc' },
      { t: '10', type: 'num' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(count)\n    count += ', type: 'punc' },
      { t: '1', type: 'num' },
      { t: '\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"반복 종료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '조건이 참인 동안 반복하는 키워드 철자를 확인하세요',
  },
  {
    id: 17,
    tokens: [
      { t: 'wihle', type: 'kw', error: true, fix: 'while' },
      { t: ' ', type: 'punc' },
      { t: 'not', type: 'kw' },
      { t: ' is_ready:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"준비 중..."', type: 'str' },
      { t: ')\n    is_ready = ', type: 'punc' },
      { t: 'check_status', type: 'kw' },
      { t: '()\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"준비 완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '조건이 참인 동안 반복하는 키워드 철자를 확인하세요',
  },
  {
    id: 18,
    tokens: [
      { t: 'whle', type: 'kw', error: true, fix: 'while' },
      { t: ' stock > ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: ':\n    ', type: 'punc' },
      { t: 'sell_one', type: 'kw' },
      { t: '()\n    stock -= ', type: 'punc' },
      { t: '1', type: 'num' },
      { t: '\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"재고 소진"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '조건이 참인 동안 반복하는 키워드 철자를 확인하세요',
  },
  {
    id: 19,
    tokens: [
      { t: 'whiel', type: 'kw', error: true, fix: 'while' },
      { t: ' ', type: 'punc' },
      { t: 'True', type: 'kw' },
      { t: ':\n    answer = ', type: 'punc' },
      { t: 'input', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"종료하려면 q: "', type: 'str' },
      { t: ')\n    ', type: 'punc' },
      { t: 'if', type: 'kw' },
      { t: ' answer == ', type: 'punc' },
      { t: '"q"', type: 'str' },
      { t: ':\n        ', type: 'punc' },
      { t: 'break', type: 'kw' },
    ],
    hint: '조건이 참인 동안 반복하는 키워드 철자를 확인하세요',
  },
  {
    id: 20,
    tokens: [
      { t: 'fro', type: 'kw', error: true, fix: 'for' },
      { t: ' i ', type: 'punc' },
      { t: 'in', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'range', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '5', type: 'num' },
      { t: '):\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: 'f"현재 숫자: {i}"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"반복문 종료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '반복문을 시작하는 키워드 철자를 확인하세요',
  },
  {
    id: 21,
    tokens: [
      { t: 'ofr', type: 'kw', error: true, fix: 'for' },
      { t: ' fruit ', type: 'punc' },
      { t: 'in', type: 'kw' },
      { t: ' [', type: 'punc' },
      { t: '"사과"', type: 'str' },
      { t: ', ', type: 'punc' },
      { t: '"바나나"', type: 'str' },
      { t: ', ', type: 'punc' },
      { t: '"포도"', type: 'str' },
      { t: ']:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: 'f"과일: {fruit}"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"출력 완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '반복문을 시작하는 키워드 철자를 확인하세요',
  },
  {
    id: 22,
    tokens: [
      { t: 'fo', type: 'kw', error: true, fix: 'for' },
      { t: ' student ', type: 'punc' },
      { t: 'in', type: 'kw' },
      { t: ' students:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(student.name)\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(student.score)', type: 'punc' },
    ],
    hint: '반복문을 시작하는 키워드 철자를 확인하세요',
  },
  {
    id: 23,
    tokens: [
      { t: 'forr', type: 'kw', error: true, fix: 'for' },
      { t: ' i ', type: 'punc' },
      { t: 'in', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'range', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '1', type: 'num' },
      { t: ', ', type: 'punc' },
      { t: '11', type: 'num' },
      { t: '):\n    total += i\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: 'f"합계: {total}"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '반복문을 시작하는 키워드 철자를 확인하세요',
  },
  {
    id: 24,
    tokens: [
      { t: 'for', type: 'kw' },
      { t: ' i ', type: 'punc' },
      { t: 'ni', type: 'kw', error: true, fix: 'in' },
      { t: ' ', type: 'punc' },
      { t: 'range', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '3', type: 'num' },
      { t: '):\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(i)\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '반복 대상 앞에 오는 키워드 철자를 확인하세요',
  },
  {
    id: 25,
    tokens: [
      { t: 'if', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: '"python"', type: 'str' },
      { t: ' ', type: 'punc' },
      { t: 'ib', type: 'kw', error: true, fix: 'in' },
      { t: ' [', type: 'punc' },
      { t: '"java"', type: 'str' },
      { t: ', ', type: 'punc' },
      { t: '"python"', type: 'str' },
      { t: ', ', type: 'punc' },
      { t: '"c"', type: 'str' },
      { t: ']:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"찾았습니다"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"없습니다"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '포함 여부를 확인하는 키워드 철자를 확인하세요',
  },
  {
    id: 26,
    tokens: [
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'add', type: 'kw' },
      { t: '(a, b):\n    result = a + b\n    ', type: 'punc' },
      { t: 'retrun', type: 'kw', error: true, fix: 'return' },
      { t: '\n    result', type: 'punc' },
    ],
    hint: '함수 결과값을 돌려주는 키워드 철자를 확인하세요',
  },
  {
    id: 27,
    tokens: [
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'multiply', type: 'kw' },
      { t: '(a, b):\n    ', type: 'punc' },
      { t: 'retun', type: 'kw', error: true, fix: 'return' },
      { t: '\n    a * b', type: 'punc' },
    ],
    hint: '함수 결과값을 돌려주는 키워드 철자를 확인하세요',
  },
  {
    id: 28,
    tokens: [
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'get_max', type: 'kw' },
      { t: '(a, b):\n    ', type: 'punc' },
      { t: 'if', type: 'kw' },
      { t: ' a > b:\n        ', type: 'punc' },
      { t: 'rturn', type: 'kw', error: true, fix: 'return' },
      { t: '\n    ', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n        ', type: 'punc' },
      { t: 'return', type: 'kw' },
      { t: ' b', type: 'punc' },
    ],
    hint: '함수 결과값을 돌려주는 키워드 철자를 확인하세요',
  },
  {
    id: 29,
    tokens: [
      { t: 'improt', type: 'kw', error: true, fix: 'import' },
      { t: ' random\nnumber = random.', type: 'punc' },
      { t: 'randint', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '1', type: 'num' },
      { t: ', ', type: 'punc' },
      { t: '10', type: 'num' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(number)', type: 'punc' },
    ],
    hint: '모듈을 가져올 때 쓰는 키워드 철자를 확인하세요',
  },
  {
    id: 30,
    tokens: [
      { t: 'imprt', type: 'kw', error: true, fix: 'import' },
      { t: ' datetime\nnow = datetime.datetime.', type: 'punc' },
      { t: 'now', type: 'kw' },
      { t: '()\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(now)', type: 'punc' },
    ],
    hint: '모듈을 가져올 때 쓰는 키워드 철자를 확인하세요',
  },
  {
    id: 31,
    tokens: [
      { t: 'form', type: 'kw', error: true, fix: 'from' },
      { t: ' os\n', type: 'punc' },
      { t: 'import', type: 'kw' },
      { t: ' path\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(path.', type: 'punc' },
      { t: 'exists', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"data.txt"', type: 'str' },
      { t: '))', type: 'punc' },
    ],
    hint: '다른 모듈에서 가져올 때 쓰는 키워드 철자를 확인하세요',
  },
  {
    id: 32,
    tokens: [
      { t: 'import', type: 'kw' },
      { t: ' numpy ', type: 'punc' },
      { t: 'sa', type: 'kw', error: true, fix: 'as' },
      { t: ' np\narr = np.', type: 'punc' },
      { t: 'array', type: 'kw' },
      { t: '([', type: 'punc' },
      { t: '1', type: 'num' },
      { t: ', ', type: 'punc' },
      { t: '2', type: 'num' },
      { t: ', ', type: 'punc' },
      { t: '3', type: 'num' },
      { t: '])\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(arr)', type: 'punc' },
    ],
    hint: '별칭을 붙일 때 쓰는 키워드 철자를 확인하세요',
  },
  {
    id: 33,
    tokens: [
      { t: 'is_ready = ', type: 'punc' },
      { t: 'Ture', type: 'kw', error: true, fix: 'True' },
      { t: '\n', type: 'punc' },
      { t: 'if', type: 'kw' },
      { t: ' is_ready:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"준비 완료"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"대기 중"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '참을 뜻하는 값의 철자를 확인하세요',
  },
  {
    id: 34,
    tokens: [
      { t: 'is_done = ', type: 'punc' },
      { t: 'Flase', type: 'kw', error: true, fix: 'False' },
      { t: '\n', type: 'punc' },
      { t: 'while', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'not', type: 'kw' },
      { t: ' is_done:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"작업 중..."', type: 'str' },
      { t: ')\n    is_done = ', type: 'punc' },
      { t: 'True', type: 'kw' },
    ],
    hint: '거짓을 뜻하는 값의 철자를 확인하세요',
  },
  {
    id: 35,
    tokens: [
      { t: 'result = ', type: 'punc' },
      { t: 'Noen', type: 'kw', error: true, fix: 'None' },
      { t: '\n', type: 'punc' },
      { t: 'if', type: 'kw' },
      { t: ' result ', type: 'punc' },
      { t: 'is', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'None', type: 'kw' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"결과 없음"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'else', type: 'kw' },
      { t: ':\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(result)', type: 'punc' },
    ],
    hint: '값이 없음을 뜻하는 키워드 철자를 확인하세요',
  },
  {
    id: 36,
    tokens: [
      { t: 'tyr', type: 'kw', error: true, fix: 'try' },
      { t: '\n    num = ', type: 'punc' },
      { t: 'int', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"abc"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'except', type: 'kw' },
      { t: ' ValueError:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"숫자가 아닙니다"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"처리 완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '예외가 발생할 수 있는 코드 블록을 시작하는 키워드예요',
  },
  {
    id: 37,
    tokens: [
      { t: 'try', type: 'kw' },
      { t: ':\n    num = ', type: 'punc' },
      { t: 'int', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"abc"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'excpet', type: 'kw', error: true, fix: 'except' },
      { t: '\n ValueError:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"변환 오류"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"처리 완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '예외를 처리하는 블록 키워드 철자를 확인하세요',
  },
  {
    id: 38,
    tokens: [
      { t: 'try', type: 'kw' },
      { t: ':\n    file = ', type: 'punc' },
      { t: 'open', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"data.txt"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'except', type: 'kw' },
      { t: ' FileNotFoundError:\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"파일 없음"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'finaly', type: 'kw', error: true, fix: 'finally' },
      { t: '\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"작업 종료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '항상 실행되는 블록 키워드 철자를 확인하세요',
  },
  {
    id: 39,
    tokens: [
      { t: 'for', type: 'kw' },
      { t: ' i ', type: 'punc' },
      { t: 'in', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'range', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '10', type: 'num' },
      { t: '):\n    ', type: 'punc' },
      { t: 'if', type: 'kw' },
      { t: ' i == ', type: 'punc' },
      { t: '5', type: 'num' },
      { t: ':\n        ', type: 'punc' },
      { t: 'braek', type: 'kw', error: true, fix: 'break' },
      { t: '\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(i)\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"반복 종료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '반복문을 즉시 멈추는 키워드 철자를 확인하세요',
  },
  {
    id: 40,
    tokens: [
      { t: 'for', type: 'kw' },
      { t: ' i ', type: 'punc' },
      { t: 'in', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'range', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '10', type: 'num' },
      { t: '):\n    ', type: 'punc' },
      { t: 'if', type: 'kw' },
      { t: ' i % ', type: 'punc' },
      { t: '2', type: 'num' },
      { t: ' == ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: ':\n        ', type: 'punc' },
      { t: 'contineu', type: 'kw', error: true, fix: 'continue' },
      { t: '\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(i)\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"홀수만 출력 완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '현재 반복만 건너뛰는 키워드 철자를 확인하세요',
  },
  {
    id: 41,
    tokens: [
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'todo', type: 'kw' },
      { t: '():\n    ', type: 'punc' },
      { t: 'pas', type: 'kw', error: true, fix: 'pass' },
      { t: '\n\n', type: 'punc' },
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'done', type: 'kw' },
      { t: '():\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"완료됨"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '아무 동작도 하지 않는 키워드 철자를 확인하세요',
  },
  {
    id: 42,
    tokens: [
      { t: 'calss', type: 'kw', error: true, fix: 'class' },
      { t: ' Dog:\n    ', type: 'punc' },
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: '__init__', type: 'kw' },
      { t: '(self, name):\n        self.name = name\n    ', type: 'punc' },
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'bark', type: 'kw' },
      { t: '(self):\n        ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"멍멍"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '클래스를 정의하는 키워드 철자를 확인하세요',
  },
  {
    id: 43,
    tokens: [
      { t: 'clas', type: 'kw', error: true, fix: 'class' },
      { t: ' BankAccount:\n    ', type: 'punc' },
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: '__init__', type: 'kw' },
      { t: '(self, balance):\n        self.balance = balance\n    ', type: 'punc' },
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'deposit', type: 'kw' },
      { t: '(self, amt):\n        self.balance += amt', type: 'punc' },
    ],
    hint: '클래스를 정의하는 키워드 철자를 확인하세요',
  },
  {
    id: 44,
    tokens: [
      { t: 'square = ', type: 'punc' },
      { t: 'lamda', type: 'kw', error: true, fix: 'lambda' },
      { t: ' x: x * x\nnums = [', type: 'punc' },
      { t: '1', type: 'num' },
      { t: ', ', type: 'punc' },
      { t: '2', type: 'num' },
      { t: ', ', type: 'punc' },
      { t: '3', type: 'num' },
      { t: ', ', type: 'punc' },
      { t: '4', type: 'num' },
      { t: ']\nresult = ', type: 'punc' },
      { t: 'list', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: 'map', type: 'kw' },
      { t: '(square, nums))\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(result)', type: 'punc' },
    ],
    hint: '이름 없는 함수를 만드는 키워드 철자를 확인하세요',
  },
  {
    id: 45,
    tokens: [
      { t: 'count = ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: '\n', type: 'punc' },
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'increment', type: 'kw' },
      { t: '():\n    ', type: 'punc' },
      { t: 'globl', type: 'kw', error: true, fix: 'global' },
      { t: ' count\n    count += ', type: 'punc' },
      { t: '1', type: 'num' },
      { t: '\n\n', type: 'punc' },
      { t: 'increment', type: 'kw' },
      { t: '()\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(count)', type: 'punc' },
    ],
    hint: '전역 변수를 사용하겠다는 키워드 철자를 확인하세요',
  },
  {
    id: 46,
    tokens: [
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'outer', type: 'kw' },
      { t: '():\n    x = ', type: 'punc' },
      { t: '1', type: 'num' },
      { t: '\n    ', type: 'punc' },
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'inner', type: 'kw' },
      { t: '():\n        ', type: 'punc' },
      { t: 'nonlcoal', type: 'kw', error: true, fix: 'nonlocal' },
      { t: ' x\n        x += ', type: 'punc' },
      { t: '1', type: 'num' },
      { t: '\n    ', type: 'punc' },
      { t: 'inner', type: 'kw' },
      { t: '()\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(x)', type: 'punc' },
    ],
    hint: '바깥 함수의 변수를 사용하겠다는 키워드 철자를 확인하세요',
  },
  {
    id: 47,
    tokens: [
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'counter', type: 'kw' },
      { t: '():\n    n = ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: '\n    ', type: 'punc' },
      { t: 'while', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'True', type: 'kw' },
      { t: ':\n        ', type: 'punc' },
      { t: 'yeild', type: 'kw', error: true, fix: 'yield' },
      { t: ' n\n        n += ', type: 'punc' },
      { t: '1', type: 'num' },
      { t: '\n\n', type: 'punc' },
      { t: 'for', type: 'kw' },
      { t: ' val ', type: 'punc' },
      { t: 'in', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'counter', type: 'kw' },
      { t: '():\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(val)', type: 'punc' },
    ],
    hint: '값을 하나씩 반환하는 제너레이터 키워드 철자를 확인하세요',
  },
  {
    id: 48,
    tokens: [
      { t: 'def', type: 'kw' },
      { t: ' ', type: 'punc' },
      { t: 'check_age', type: 'kw' },
      { t: '(age):\n    ', type: 'punc' },
      { t: 'if', type: 'kw' },
      { t: ' age < ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: ':\n        ', type: 'punc' },
      { t: 'rasie', type: 'kw', error: true, fix: 'raise' },
      { t: ' ', type: 'punc' },
      { t: 'ValueError', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"나이는 음수일 수 없습니다"', type: 'str' },
      { t: ')\n    ', type: 'punc' },
      { t: 'return', type: 'kw' },
      { t: ' age', type: 'punc' },
    ],
    hint: '예외를 직접 발생시키는 키워드 철자를 확인하세요',
  },
  {
    id: 49,
    tokens: [
      { t: 'wiht', type: 'kw', error: true, fix: 'with' },
      { t: ' ', type: 'punc' },
      { t: 'open', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"data.txt"', type: 'str' },
      { t: ') ', type: 'punc' },
      { t: 'as', type: 'kw' },
      { t: ' f:\n    data = f.', type: 'punc' },
      { t: 'read', type: 'kw' },
      { t: '()\n    ', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(data)\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"파일 처리 완료"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '파일이나 자원을 안전하게 여는 키워드 철자를 확인하세요',
  },
  {
    id: 50,
    tokens: [
      { t: 'asert', type: 'kw', error: true, fix: 'assert' },
      { t: ' age >= ', type: 'punc' },
      { t: '0', type: 'num' },
      { t: ', ', type: 'punc' },
      { t: '"나이는 음수일 수 없습니다"', type: 'str' },
      { t: '\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: '"검증 통과"', type: 'str' },
      { t: ')\n', type: 'punc' },
      { t: 'print', type: 'kw' },
      { t: '(', type: 'punc' },
      { t: 'f"나이: {age}"', type: 'str' },
      { t: ')', type: 'punc' },
    ],
    hint: '조건이 참인지 검사하는 키워드 철자를 확인하세요',
  },
];

// 전체 문제 풀(50개). 한 판에는 이 중 STAGE_COUNT개만 뽑아서(useTapGame에서 셔플 후 slice) 사용함.
export const BOMB_QUESTIONS = RAW_QUESTIONS;

// 한 판당 스테이지 수 — 50문제 풀에서 이 개수만큼 셔플해서 뽑아 사용
export const STAGE_COUNT = 10;

// (하위 호환용) 문제 풀 전체 개수가 필요한 곳에서 사용
export const TOTAL_QUESTIONS = BOMB_QUESTIONS.length;
