export const PAIRS = [
  { "id": 1,  "concept": { "type": "concept", "text": "변수 선언" },          "code": { "type": "code", "text": "name = \"Amy\"" } },
  { "id": 2,  "concept": { "type": "concept", "text": "정수\n입력 받기" },     "code": { "type": "code", "text": "num =\nint(input())" } },
  { "id": 3,  "concept": { "type": "concept", "text": "조건문 (if)" },        "code": { "type": "code", "text": "if score >= 80:" } },
  { "id": 4,  "concept": { "type": "concept", "text": "elif 분기" },          "code": { "type": "code", "text": "elif score >= 60:" } },
  { "id": 5,  "concept": { "type": "concept", "text": "for 반복문" },         "code": { "type": "code", "text": "for i in range(5):" } },
  { "id": 6,  "concept": { "type": "concept", "text": "while 반복문" },       "code": { "type": "code", "text": "while n > 0:" } },
  { "id": 7,  "concept": { "type": "concept", "text": "리스트 생성" },        "code": { "type": "code", "text": "items = [1, 2, 3]" } },
  { "id": 8,  "concept": { "type": "concept", "text": "리스트\n항목 추가" },   "code": { "type": "code", "text": "items.append(4)" } },
  { "id": 9,  "concept": { "type": "concept", "text": "함수 정의" },          "code": { "type": "code", "text": "def add(a, b):" } },
  { "id": 10, "concept": { "type": "concept", "text": "함수 반환값" },        "code": { "type": "code", "text": "return a + b" } },
  { "id": 11, "concept": { "type": "concept", "text": "f-문자열" },           "code": { "type": "code", "text": "msg =\nf\"점수: {score}점\"" } },
  { "id": 12, "concept": { "type": "concept", "text": "딕셔너리 생성" },      "code": { "type": "code", "text": "info =\n{\"name\": \"Amy\"}" } },

  { "id": 13, "concept": { "type": "concept", "text": "문자열\n슬라이싱" },    "code": { "type": "code", "text": "text[0:3]" } },
  { "id": 14, "concept": { "type": "concept", "text": "문자열\n대문자 변환" }, "code": { "type": "code", "text": "\"hello\".upper()" } },
  { "id": 15, "concept": { "type": "concept", "text": "논리 연산자\nAND" },   "code": { "type": "code", "text": "x > 0 and x < 10" } },
  { "id": 16, "concept": { "type": "concept", "text": "반복\n강제 종료" },     "code": { "type": "code", "text": "break" } },
  { "id": 17, "concept": { "type": "concept", "text": "리스트\n오름차순 정렬" },"code": { "type": "code", "text": "scores.sort()" } },
  { "id": 18, "concept": { "type": "concept", "text": "딕셔너리\n값 접근" },   "code": { "type": "code", "text": "person[\"name\"]" } },
  { "id": 19, "concept": { "type": "concept", "text": "세트 생성" },          "code": { "type": "code", "text": "nums = {1, 2, 3}" } },
  { "id": 20, "concept": { "type": "concept", "text": "기본값\n매개변수" },    "code": { "type": "code", "text": "def greet(\nname=\"Amy\"):" } },
  { "id": 21, "concept": { "type": "concept", "text": "특정\n예외 처리" },     "code": { "type": "code", "text": "except ValueError:" } },
  { "id": 22, "concept": { "type": "concept", "text": "람다 함수" },          "code": { "type": "code", "text": "lambda x: x ** 2" } },
  { "id": 23, "concept": { "type": "concept", "text": "리스트\n컴프리헨션" },  "code": { "type": "code", "text": "[x*2 for\nx in nums]" } },
  { "id": 24, "concept": { "type": "concept", "text": "클래스 정의" },        "code": { "type": "code", "text": "class Dog:" } },

  { "id": 25, "concept": { "type": "concept", "text": "화면 출력" },          "code": { "type": "code", "text": "print(\"Hello!\")" } },
  { "id": 26, "concept": { "type": "concept", "text": "자료형 확인" },        "code": { "type": "code", "text": "type(42)" } },
  { "id": 27, "concept": { "type": "concept", "text": "숫자 → 문자\n변환" },  "code": { "type": "code", "text": "str(100)" } },
  { "id": 28, "concept": { "type": "concept", "text": "문자열\n끝 인덱싱" },   "code": { "type": "code", "text": "text[-1]" } },
  { "id": 29, "concept": { "type": "concept", "text": "문자열\n공백 제거" },   "code": { "type": "code", "text": "\"  hi  \".strip()" } },
  { "id": 30, "concept": { "type": "concept", "text": "문자열 분리" },        "code": { "type": "code", "text": "\"a,b,c\".split(\",\")" } },
  { "id": 31, "concept": { "type": "concept", "text": "문자열 치환" },        "code": { "type": "code", "text": "text.replace(\n\"a\", \"b\")" } },
  { "id": 32, "concept": { "type": "concept", "text": "논리 연산자\nOR" },    "code": { "type": "code", "text": "a > 5 or b > 5" } },
  { "id": 33, "concept": { "type": "concept", "text": "현재 반복\n건너뜀" },   "code": { "type": "code", "text": "continue" } },
  { "id": 34, "concept": { "type": "concept", "text": "리스트\n첫 항목 접근" },"code": { "type": "code", "text": "items[0]" } },
  { "id": 35, "concept": { "type": "concept", "text": "리스트\n항목 삭제" },   "code": { "type": "code", "text": "items.remove(3)" } },
  { "id": 36, "concept": { "type": "concept", "text": "딕셔너리\n항목 추가" }, "code": { "type": "code", "text": "person[\"age\"] = 25" } },
  { "id": 37, "concept": { "type": "concept", "text": "딕셔너리\n키 목록" },   "code": { "type": "code", "text": "person.keys()" } },
  { "id": 38, "concept": { "type": "concept", "text": "세트 교집합" },        "code": { "type": "code", "text": "set_a & set_b" } },
  { "id": 39, "concept": { "type": "concept", "text": "전역 변수\n선언" },     "code": { "type": "code", "text": "global count" } },
  { "id": 40, "concept": { "type": "concept", "text": "파일\n읽기 열기" },     "code": { "type": "code", "text": "open(\"data.txt\",\n\"r\")" } },
  { "id": 41, "concept": { "type": "concept", "text": "튜플 생성" },          "code": { "type": "code", "text": "point = (3, 5)" } },
  { "id": 42, "concept": { "type": "concept", "text": "튜플 언패킹" },        "code": { "type": "code", "text": "x, y = (3, 5)" } },
  { "id": 43, "concept": { "type": "concept", "text": "가변\n위치 인자" },     "code": { "type": "code", "text": "def total(*args):" } },
  { "id": 44, "concept": { "type": "concept", "text": "가변\n키워드 인자" },   "code": { "type": "code", "text": "def info(**kwargs):" } },
  { "id": 45, "concept": { "type": "concept", "text": "생성자 메서드" },      "code": { "type": "code", "text": "def __init__(\nself, name):" } },
  { "id": 46, "concept": { "type": "concept", "text": "객체 생성" },          "code": { "type": "code", "text": "cat =\nAnimal(\"Nabi\")" } },
  { "id": 47, "concept": { "type": "concept", "text": "클래스 상속" },        "code": { "type": "code", "text": "class Poodle(Dog):" } },
  { "id": 48, "concept": { "type": "concept", "text": "JSON 파싱" },          "code": { "type": "code", "text": "json.loads(text)" } }
]
